name: Build Wheels and Release
on:
  push:
    tags:
      - 'v*'
      - 'buildwheels*'
env:
  CIBW_BUILD_VERBOSITY: 2
  CIBW_TEST_REQUIRES: "-r requirements/test.txt"
  CIBW_TEST_COMMAND: pytest --pyargs skimage -vv
  CIBW_ENVIRONMENT: PIP_PREFER_BINARY=1
  # (currently not avaialable for scipy)
  CIBW_ARCHS_MACOS: x86_64 # TODO: add arm64 universal2


jobs:

  build_windows_wheels:
    name: Build ${{ matrix.cibw_arch }} wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        cibw_arch: ["AMD64", "x86"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      # install choco package manager
      - uses: crazy-max/ghaction-chocolatey@v1
        name: Install chocolatey
        with:
          args: -h

      # install x86 clang-cl (needed for Pythran)
      - name: Install x86 clang-cl
        if: matrix.cibw_arch == 'x86'
        run: |
          choco install --force --x86 llvm

      # install clang-cl (needed for Pythran)
      - name: Install clang-cl
        if: matrix.cibw_arch == 'ARM64'
        run: |
          choco install --force llvm

      - name: Install cibuildwheel and add clang-cl to path
        run: |
          python -m pip install cibuildwheel
          SET PATH="C:\\Program Files\\LLVM\\bin;%PATH%"
          SET PATH="C:\\Program Files (x86)\\LLVM\\bin;%PATH%"

      - name: Build Windows wheels for CPython 3.10
        # NumPy dropped x86 wheels for Python 3.10
        if: matrix.cibw_arch == 'ARM64'
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp310-*"
          CIBW_ARCHS_WINDOWS: ${{ matrix.cibw_arch }}

      - name: Build Windows wheels for CPython
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp3?-*"
          CIBW_SKIP: "cp36-*"
          CIBW_ARCHS_WINDOWS: ${{ matrix.cibw_arch }}

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./dist/*.whl
